#!/bin/bash

#PBS -N A1_old
#PBS -e A1_old.err 
#PBS -o A1_old.out 
#PBS -l nodes=2:ppn=24 
#PBS -V 

PBS_O_WORKDIR='/home/xyhuang/OpenSMOKE_Droplet/exe/' 
export PBS_O_WORKDIR 
### --------------------------------------- 
### BEGINNING OF EXECUTION 
### --------------------------------------- 

echo The master node of this job is \`hostname\` 
echo The working directory is \`echo $PBS_O_WORKDIR\` 
echo This job runs on the following nodes: 
echo \`cat $PBS_NODEFILE\` 

### end of information preamble 

cd $PBS_O_WORKDIR

cmd="./OpenSMOKEpp_MicrogravityDroplet.sh --input ./test_simulation/input.A1.dic"

echo "Running Intel-15 MVAPICH linked bounce with: $cmd in directory "`pwd`

$cmd >& /home/xyhuang/OpenSMOKE_Droplet/exe/jobs/log.$PBS_JOBID
